### PR TITLE
Fix multiple round pass issue #66

### LINKED ISSUE #66: Multiple round processing is ignoring newly generated files
**Describe the bug**
I'm trying to add new feature to another ksp processing library that will automatically generate `@Single` or `@Factory` annotation for files that are generated by ksp. But the koin processor does not process those newly generated files and i think the reason is usage of flag `codeGenerated` here https://github.com/InsertKoinIO/koin-annotations/blob/main/compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/BuilderProcessor.kt#L32. AFAIK this shouldn't be used like that, because even if the processor is done with all classes from my source it can be still called with new classes that are generated by another ksp processor. Is this flag even necessary? Ksp is automatically filtering classes that are processed. Looking at official example (https://github.com/google/ksp/blob/main/examples/playground/test-processor/src/main/kotlin/BuilderProcessor.kt) the processor should store the list of invalid classes, process the valid ones and then result list of invalid ones so it can be called later with of those classes. I think i can do a PR with that if you're open to my suggestion.

PS. Do you have tests for generated code?

**To Reproduce**
1. Create an ksp processor that generates class with `@Single` annotation
2. Setup a koin project that tries to use that class by `AppModule().module`
3. Project does not comple, module with the configuration for generated class does not get generated

Project that can be reproduced on: https://github.com/jakoss/kmapper/blob/feature/di-integration/examples/koin/src/main/kotlin/com/syouth/kmapper/koin/Main.kt

**Expected behavior**
Koin should properly generate injection configuration for code that is generated by another ksp processors

**Koin project used and used version (please complete the following information):**
`koin-ksp-processor version 1.1.0`

### PR DESCRIPTION
**Pull request by jakoss**
This PR removes the "stop processing" flag since there might be some code to process that was not available in the first round of ksp processing.

For example: Koin was able to successfully do a first round, where the compiler found `@Module` and `@ComponentScan`. The code was generated and the `codeGenerated` flag was set to true. The issue is that some other ksp processor did generate a new class during the first round. The new class has `@Single` annotation, but it was ignored since the `codeGenerated` flag was shutting further processing down.

This fix makes the processor able to do multiple rounds on the same symbols and recreating generated modules file contents if necessary.

Fixes #66

### CODE REVIEW

**Comment by jakoss** [comment]
@gbourassa @arnaudgiuliani Do you have some larger codebases that you can test this on? I'm feeling a little bit unsecure since i don't have a large codebase using koin annotations and there are no tests

**Comment by jakoss** [comment]
@gbourassa I absolutely don't blame you, I just found i case where the flag breaks the assumption of multiple round processing 😁. Please take a look at my pull request, I think It fixes the issue. If you could try that on your codebases just to make sure

**Comment by gbourassa** [comment]
@jakoss No blame taken, don't worry :)

I just tried your code, and it work perfectly with my use case 🎉 

After testing my version _without_ the `codeGenerated` flag, I remembered the issue I was trying to solve (there was a 3rd round that was invoked after Koin generated its stuff, and that was crashing when trying to write another time in the File). Your solution to this issue (improving `getDefaultFile`) is much better! Good work!

I approve this 👍

File: compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinGenerator.kt [hunk 1]
```diff
@@ -43,19 +43,20 @@ class KoinGenerator(
 
         if (defaultModule.definitions.isNotEmpty()) {
             logger.logging("generate default module ...")
-            val defaultModuleFile = codeGenerator.getDefaultFile()
+            val defaultModuleFile = codeGenerator.getFile(fileName = "Default")
```
Comment (arnaudgiuliani) [inline compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinGenerator.kt:46]: is it the same here?

Comment (jakoss) [reply compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinGenerator.kt:46]: getDefaultFile cached default file as local field with cause issue with multiple pass and wasn't necessary. The result behavior is the same, but without local field

Comment (arnaudgiuliani) [reply compiler/koin-ksp-compiler/src/jvmMain/kotlin/org/koin/compiler/generator/KoinGenerator.kt:46]: ok, got it

**Comment by jakoss** [comment]
@arnaudgiuliani any update on review here? Maybe you could somehow release a snapshot version of this to maven so more people can test it out in the wild. I think we have issue similar to https://github.com/InsertKoinIO/koin-annotations/issues/69 and we would like to test it out

**Comment by arnaudgiuliani** [comment]
preparing beta version to have feedback yes 👍
